# Site settings
title: SP 800-63 Digital Identity Guidelines
description: "NIST Special Publication 800-63 Digital Identity Guidelines"
baseurl: "/800-63-4" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md
- BUILD.md
- "*.yml"
- "*/images/*.pdf"

# GitHub information
org_name: usnistgov
repo_name: 800-63-4

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /
- text: SP 800-63
  url: /sp800-63/
  collection: sp800-63
- text: SP 800-63A
  url: /sp800-63a/
  collection: sp800-63a
- text: SP 800-63B
  url: /sp800-63b/
  collection: sp800-63b
- text: SP 800-63C
  url: /sp800-63c/
  collection: sp800-63c

host: 0.0.0.0

collections:
  sp800-63:
    title: "General"
    output: true
  sp800-63a:
    title: "Identity Proofing"
    output: true
  sp800-63b:
    title: "Authentication"
    output: true
  sp800-63c:
    title: "Federation and Assertions"
    output: true

relative_links:
  enabled:     true
  collections: true

abstract:
  sp800-63:
    subject: "These guidelines provide technical requirements for federal agencies implementing digital identity services and are not intended to constrain the development or use of standards outside of this purpose. The guidelines cover identity proofing and authentication of users (such as employees, contractors, or private individuals) interacting with government information systems over networks. They define technical requirements in each of the areas of identity proofing, registration, authenticators, management processes, authentication protocols, federation, and related assertions. This publication will supersede NIST Special Publication 800-63-3."
    keywords: 'authentication; authentication assurance; authenticator; assertions; credential service provider; digital authentication; digital credentials; identity proofing; federation; passwords; PKI.'
  sp800-63a:
    subject: "These guidelines provide technical requirements for federal agencies implementing digital identity services and are not intended to constrain the development or use of standards outside of this purpose. This guideline focuses on the enrollment and verification of an identity for use in digital authentication. Central to this is a process known as identity proofing in which an applicant provides evidence to a credential service provider (CSP) reliably identifying themselves, thereby allowing the CSP to assert that identification at a useful identity assurance level. This document defines technical requirements for each of three identity assurance levels. This publication will supersede NIST Special Publication (SP) 800-63A."
    keywords: 'authentication; credential service provider; electronic authentication; digital authentication; electronic credentials; digital credentials; identity proofing; federation.'
  sp800-63b:
    subject: "These guidelines provide technical requirements for federal agencies implementing digital identity services and are not intended to constrain the development or use of standards outside of this purpose. These guidelines focus on the authentication of subjects interacting with government information systems over networks, establishing that a given claimant is a subscriber who has been previously authenticated. The result of the authentication process may be used locally by the system performing the authentication or may be asserted elsewhere in a federated identity system. This document defines technical requirements for each of the three authenticator assurance levels. This publication will supersede NIST Special Publication (SP) 800-63B."
    keywords: 'authentication; authentication assurance; credential service provider; digital authentication; digital credentials; electronic authentication; electronic credentials; passwords.'
  sp800-63c:
    # subject: "These guidelines provide technical requirements for federal agencies implementing digital identity services and are not intended to constrain the development or use of standards outside of this purpose. This guideline focuses on the use of federated identity and the use of assertions to implement identity federations. Federation allows a given credential service provider to provide authentication attributes and (optionally) subscriber attributes to a number of separately-administered relying parties. Similarly, relying parties may use more than one credential service provider. This publication will supersede NIST Special Publication (SP) 800-63C."
    subject: "本ガイドライン群は, Digital Identity サービスを実装する連邦機関に対する技術的要件を提供するものであり, それ以外の条件下での標準仕様の開発・利用に対する制約を意図したものではない. 本ガイドラインは, Identity Federation の実装に際した Federated Identity および Assertion の利用にフォーカスしている. Federation は, ある Credential Service Provider が, 多数の異なる管理下にある Relying Party に対して, Authentication Attribute および (オプションで) Subscriber Attribute を提示する手段となる. 同様に, Relying Party は一つ以上の Credential Service Provider を利用可能となる. 本ドキュメントの発行をもって, 本ドキュメントは既存の NIST Special Publication (SP) 800-63C を置き換えるものとなる."
    keywords: 'assertions; authentication; credential service provider; digital authentication; electronic authentication; electronic credentials; federations.'
